AWS_UPLOAD_BUCKET = "cfe-awesome-bucket"

AWS_UPLOAD_USERNAME = "CFE_user_justin"

AWS_UPLOAD_GROUP = "CFE_AwesomeGroup"

AWS_UPLOAD_REGION = 'us-west-2'

AWS_UPLOAD_ACCESS_KEY_ID = "AKIAJQEJZQD6WMEQIK7A"

AWS_UPLOAD_SECRET_KEY = "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"