# Generated by Django 2.2.6 on 2019-10-19 02:30

import UploadImage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadImage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=UploadImage.models.nameFile),
        ),
    ]
